// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0--rc3
// source: userbot.proto

package userbotpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetChannelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChannelRequest) Reset() {
	*x = GetChannelRequest{}
	mi := &file_userbot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChannelRequest) ProtoMessage() {}

func (x *GetChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userbot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChannelRequest.ProtoReflect.Descriptor instead.
func (*GetChannelRequest) Descriptor() ([]byte, []int) {
	return file_userbot_proto_rawDescGZIP(), []int{0}
}

func (x *GetChannelRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ChannelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	AccessHash    int64                  `protobuf:"varint,4,opt,name=access_hash,json=accessHash,proto3" json:"access_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelResponse) Reset() {
	*x = ChannelResponse{}
	mi := &file_userbot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelResponse) ProtoMessage() {}

func (x *ChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userbot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelResponse.ProtoReflect.Descriptor instead.
func (*ChannelResponse) Descriptor() ([]byte, []int) {
	return file_userbot_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelResponse) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *ChannelResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ChannelResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChannelResponse) GetAccessHash() int64 {
	if x != nil {
		return x.AccessHash
	}
	return 0
}

type MessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	AccessHash    int64                  `protobuf:"varint,2,opt,name=access_hash,json=accessHash,proto3" json:"access_hash,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagesRequest) Reset() {
	*x = MessagesRequest{}
	mi := &file_userbot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesRequest) ProtoMessage() {}

func (x *MessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userbot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesRequest.ProtoReflect.Descriptor instead.
func (*MessagesRequest) Descriptor() ([]byte, []int) {
	return file_userbot_proto_rawDescGZIP(), []int{2}
}

func (x *MessagesRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *MessagesRequest) GetAccessHash() int64 {
	if x != nil {
		return x.AccessHash
	}
	return 0
}

func (x *MessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessagesResponse) Reset() {
	*x = MessagesResponse{}
	mi := &file_userbot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessagesResponse) ProtoMessage() {}

func (x *MessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userbot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessagesResponse.ProtoReflect.Descriptor instead.
func (*MessagesResponse) Descriptor() ([]byte, []int) {
	return file_userbot_proto_rawDescGZIP(), []int{3}
}

func (x *MessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Date          int64                  `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_userbot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_userbot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_userbot_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	AccessHash    int64                  `protobuf:"varint,2,opt,name=access_hash,json=accessHash,proto3" json:"access_hash,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_userbot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userbot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_userbot_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SendMessageRequest) GetAccessHash() int64 {
	if x != nil {
		return x.AccessHash
	}
	return 0
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_userbot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userbot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_userbot_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_userbot_proto protoreflect.FileDescriptor

const file_userbot_proto_rawDesc = "" +
	"\n" +
	"\ruserbot.proto\x12\auserbot\"/\n" +
	"\x11GetChannelRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"}\n" +
	"\x0fChannelResponse\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1f\n" +
	"\vaccess_hash\x18\x04 \x01(\x03R\n" +
	"accessHash\"a\n" +
	"\x0fMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x1f\n" +
	"\vaccess_hash\x18\x02 \x01(\x03R\n" +
	"accessHash\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"@\n" +
	"\x10MessagesResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.userbot.MessageR\bmessages\"P\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12\x12\n" +
	"\x04date\x18\x03 \x01(\x03R\x04date\"b\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x1f\n" +
	"\vaccess_hash\x18\x02 \x01(\x03R\n" +
	"accessHash\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"/\n" +
	"\x13SendMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xf7\x01\n" +
	"\x0eUserbotService\x12L\n" +
	"\x14GetChannelByUsername\x12\x1a.userbot.GetChannelRequest\x1a\x18.userbot.ChannelResponse\x12M\n" +
	"\x16GetMessagesFromChannel\x12\x18.userbot.MessagesRequest\x1a\x19.userbot.MessagesResponse\x12H\n" +
	"\vSendMessage\x12\x1b.userbot.SendMessageRequest\x1a\x1c.userbot.SendMessageResponseB\fZ\n" +
	"/userbotpbb\x06proto3"

var (
	file_userbot_proto_rawDescOnce sync.Once
	file_userbot_proto_rawDescData []byte
)

func file_userbot_proto_rawDescGZIP() []byte {
	file_userbot_proto_rawDescOnce.Do(func() {
		file_userbot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_userbot_proto_rawDesc), len(file_userbot_proto_rawDesc)))
	})
	return file_userbot_proto_rawDescData
}

var file_userbot_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_userbot_proto_goTypes = []any{
	(*GetChannelRequest)(nil),   // 0: userbot.GetChannelRequest
	(*ChannelResponse)(nil),     // 1: userbot.ChannelResponse
	(*MessagesRequest)(nil),     // 2: userbot.MessagesRequest
	(*MessagesResponse)(nil),    // 3: userbot.MessagesResponse
	(*Message)(nil),             // 4: userbot.Message
	(*SendMessageRequest)(nil),  // 5: userbot.SendMessageRequest
	(*SendMessageResponse)(nil), // 6: userbot.SendMessageResponse
}
var file_userbot_proto_depIdxs = []int32{
	4, // 0: userbot.MessagesResponse.messages:type_name -> userbot.Message
	0, // 1: userbot.UserbotService.GetChannelByUsername:input_type -> userbot.GetChannelRequest
	2, // 2: userbot.UserbotService.GetMessagesFromChannel:input_type -> userbot.MessagesRequest
	5, // 3: userbot.UserbotService.SendMessage:input_type -> userbot.SendMessageRequest
	1, // 4: userbot.UserbotService.GetChannelByUsername:output_type -> userbot.ChannelResponse
	3, // 5: userbot.UserbotService.GetMessagesFromChannel:output_type -> userbot.MessagesResponse
	6, // 6: userbot.UserbotService.SendMessage:output_type -> userbot.SendMessageResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_userbot_proto_init() }
func file_userbot_proto_init() {
	if File_userbot_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_userbot_proto_rawDesc), len(file_userbot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_userbot_proto_goTypes,
		DependencyIndexes: file_userbot_proto_depIdxs,
		MessageInfos:      file_userbot_proto_msgTypes,
	}.Build()
	File_userbot_proto = out.File
	file_userbot_proto_goTypes = nil
	file_userbot_proto_depIdxs = nil
}
